version: "3.9"

services:
  order-service:
    build:
      context: ./src/Ozon.Route256.Five.OrderService
      dockerfile: Dockerfile
      target: final
    restart: unless-stopped 
    ports:
      - "8904-8910:80"
    environment:
      "ConnectionStrings::SdServiceClientUrl": "http://orders-generator"
      "ConnectionStrings::LogisticsSimulatorServiceClientUrl": "http://logistics-simulator"
      "ConnectionStrings::CustomersClientUrl": "http://customer-service"
    deploy:
      replicas: 2
    depends_on:
      - service-discovery
      - customer-service
      - logistics-simulator
      - orders-database
      - kafka
  
  customer-service:
    image: gitlab-registry.ozon.dev/cs/classroom-5/teachers/five/customer-service:latest
    restart: unless-stopped
    ports:
      - "8900:80"
    depends_on:
      - customers-database
      - service-discovery
    
  logistics-simulator:
    image: gitlab-registry.ozon.dev/cs/classroom-5/teachers/five/logistics-simulator:latest
    restart: unless-stopped
    ports:
      - "8901:80"
    depends_on:
      - kafka
    
  orders-generator:
    image: gitlab-registry.ozon.dev/cs/classroom-5/teachers/five/orders-generator:latest
    restart: unless-stopped
    ports:
      - "8902:80"
    depends_on:
      - kafka
      - customer-service
  
  service-discovery:
    image: gitlab-registry.ozon.dev/cs/classroom-5/teachers/five/service-discovery:latest
    ports:
      - "8903:80"
    restart: unless-stopped
    environment:
      - ROUTE256_DB_STATE=cluster:0-9:db1:1543;cluster:10-19:db2:1543;cluster1:0:db3:1543
      - ROUTE256_UPDATE_TIMEOUT=10

  
  orders-database:
    image: postgres:15.2-alpine
    restart: unless-stopped
    ports:
      - "8880:5432"
    environment:
      POSTGRES_PASSWORD: fd2ee12swq
      POSTGRES_DB: orders
      
  customers-database:
    image: postgres:15.2-alpine
    ports:
      - "8881:5432"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: fd2ee12swq
      POSTGRES_DB: customers
      
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    
  kafka:
    image: 'bitnami/kafka:latest'
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
        
  jaeger:
    restart: unless-stopped
    ports:
      - "16686:16686"
    image: jaegertracing/all-in-one:latest